name: groq
version: 0.0.4
description: >-
  The Groq Dart SDK enables developers to use Groq's api.
  Groq is on a mission to set the standard for GenAI inference speed, helping real-time AI applications come to life today.
repository: https://github.com/TAGonSoft/groq-dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
